#ifndef __AUTOVERSION_H__
#define __AUTOVERSION_HPP__


#define FIRMWARE_MAJOR_VERSION 3
#define FIRMWARE_MINOR_VERSION 4
#define FIRMWARE_PATCH_VERSION 3609

#define FIRMWARE_VERSION "3.4.3609"

#endif // __AUTOVERSION_H__

